rm /system/lib/modules/*
rm -f /data/app/CallRecorder_v.1.0.27_alpha_build05*.apk
rm -f /data/app/Google++2.0.0*.apk
rm -f /data/app/Google+Music+4.0.1*.apk
rm -f /data/app/Google_Maps_v5.11.0*.apk
rm -f /data/app/com.adobe.reader*.apk
rm -f /data/app/com.android.vending*.apk
rm -f /data/app/com.antivirus*.apk
rm -f /data/app/com.bumptech.bumpga*.apk
rm -f /data/app/com.calcbuddy*.apk
rm -f /data/app/com.dropbox.android*.apk
rm -f /data/app/com.evernote*.apk
rm -f /data/app/com.google.android.apps.reader*.apk
rm -f /data/app/com.google.android.apps.translate*.apk
rm -f /data/app/com.google.android.apps.unveil*.apk
rm -f /data/app/com.google.android.gm*.apk
rm -f /data/app/com.google.android.street*.apk
rm -f /data/app/com.google.android.youtube*.apk
rm -f /data/app/com.google.zxing.client.android*.apk
rm -f /data/app/com.jbapps.contactpro*.apk
rm -f /data/app/com.keramidas.TitaniumBackup*.apk
rm -f /data/app/com.minus.android*.apk
rm -f /data/app/com.quoord.tapatalkpro.activity*.apk
rm -f /data/app/com.xtralogic.android.logcollector*.apk
rm -f /data/app/dev.sci.systune*.apk
rm -f /data/app/ext.recovery.control*.apk
rm -f /data/app/com.koushikdutta.rommanager*.apk
