rm /data/app/CallRecorder*.apk
rm /data/app/com.adobe.reader-*.apk
rm /data/app/com.antivirus-*.apk
rm /data/app/com.bigtincan.android.adfree-*.apk
rm /data/app/com.bumptech.bumpga-*.apk
rm /data/app/com.calcbuddy-*.apk
rm /data/app/com.dropbox.android-*.apk
rm /data/app/com.evernote-*.apk
rm /data/app/com.google.android.apps.maps-*.apk
rm /data/app/com.google.android.apps.plus-*.apk
rm /data/app/com.google.android.apps.reader-*.apk
rm /data/app/com.google.android.apps.translate-*.apk
rm /data/app/com.google.android.apps.unveil-*.apk
rm /data/app/com.google.android.gm-*.apk
rm /data/app/com.google.android.street-*.apk
rm /data/app/com.google.android.youtube-*.apk
rm /data/app/com.google.zxing.client.android-*.apk
rm /data/app/com.jbapps.contactpro-*.apk
rm /data/app/com.keramidas.TitaniumBackup-*.apk
rm /data/app/com.minus.android-*.apk
rm /data/app/com.quoord.tapatalkpro.activity-*.apk
rm /data/app/com.xtralogic.android.logcollector-*.apk
rm /data/app/dev.sci.systune-*.apk
rm /data/app/ext.recovery.control-*.apk
