#!/system/bin/sh
# Default governor settings

SELF=`basename $0`
DEBUG=1
DEBUGF=/data/local/governor.debug
CPUFREQ="/sys/devices/system/cpu/cpufreq"
GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`

echod () {
    [ "$DEBUG" -eq 1 ] && echo $1 | tee -a $DEBUGF || echo $1
}

abort () {
    echod $1
    exit 1
}

governor_value () {
    state=$1
    cpufreq="${CPUFREQ}/${GOVERNOR}"
    echod "== Select Governor:: $GOVERNOR =="
    case "${GOVERNOR}" in
	ondemand)
	    for f in down_differential sampling_down_factor ignore_nice_load up_threshold \
		powersave_bias sampling_rate io_is_busy
    	    do
	    	echod " $state [$f]: [$(cat ${cpufreq}/${f})]"
    	    done
    	    echod " $state [sched_compat_yield]: [$(cat /proc/sys/kernel/sched_compat_yield)]"
	    ;;
	*) echod " $GOVERNOR : Unimplemented";;
    esac
}
		
ondemand_setup () {
    cpufreq="${CPUFREQ}/${GOVERNOR}"
    governor_value

    echo "15" >    ${cpufreq}/down_differential
    echo "50" >    ${cpufreq}/sampling_down_factor
    echo "0" >     ${cpufreq}/ignore_nice_load
    echo "85" >    ${cpufreq}/up_threshold
    echo "150" >   ${cpufreq}/powersave_bias
    echo "80000" > ${cpufreq}/sampling_rate
    echo "1" >     ${cpufreq}/io_is_busy
# Better thread behavior
    echo "0" > /proc/sys/kernel/sched_compat_yield

    governor_value "= modify "
}

help () {
    echo "$SELF [governor | value]"
    echo "    governor: ondemand"
}

umask 022


test -f $DEBUGF && rm -f $DEBUGF

case "$SELF" in
    governor)
        if [ "$#" -eq 1 ]; then
            case "$1" in
                ondemand)
                    ondemand_setup;;
                value)
                    governor_value;;
                *)
                    echod "$1 not supported";;
            esac
        else
            help
        fi
        ;;
    *)
        case "$GOVERNOR" in
            ondemand)
                ondemand_setup;;
            *)
                echod "$GOVERNOR: not enough setup"
                ;;
        esac
        ;;
esac
