#!/system/bin/sh
# Default governor settings

SELF=`basename $0`
DEBUG=1
DEBUGF=/data/local/governor.debug
CPUFREQ="/sys/devices/system/cpu/cpufreq"

echod () {
    [ "$DEBUG" -eq 1 ] && echo $1 | tee -a $DEBUGF || echo $1
}

abort () {
    echod $1
    exit 1
}

ondemand_setup () {
    CPUFREQ="${CPUFREQ}/${1}"
    echod "Select Governor: $1"
    for f in down_differential sampling_down_factor ignore_nice_load up_threshold \
    powersave_bias sampling_rate io_is_busy
    do
	echod " - current $f : $(cat ${CPUFREQ}/${f})"
    done
    echod " - current sched_compat_yield : $(cat /proc/sys/kernel/sched_compat_yield)"

    echo "15" >    ${CPUFREQ}/down_differential
    echo "50" >    ${CPUFREQ}/sampling_down_factor
    echo "0" >     ${CPUFREQ}/ignore_nice_load
    echo "85" >    ${CPUFREQ}/up_threshold
    echo "150" >   ${CPUFREQ}/powersave_bias
    echo "80000" > ${CPUFREQ}/sampling_rate
    echo "1" >     ${CPUFREQ}/io_is_busy
# Better thread behavior
    echo "0" > /proc/sys/kernel/sched_compat_yield

    for f in down_differential sampling_down_factor ignore_nice_load up_threshold \
	powersave_bias sampling_rate io_is_busy
    do
	echod " = modify  $f : $(cat ${CPUFREQ}/${f})"
    done
    echod " = modify  sched_compat_yield : $(cat /proc/sys/kernel/sched_compat_yield)"
}

help () {
    echo "$SELF [governor]"
    echo "    governor: ondemand"
}

umask 022
GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
test -f $DEBUGF && rm -f $DEBUGF

case "$SELF" in
    governor)
        if [ "$#" -eq 1 ]; then
            case "$1" in
                ondemand)
                    ondemand_setup $1;;
                *)
                    echod "$1 not supported";;
            esac
        else
            help
        fi
        ;;
    *)
        case "$GOVERNOR" in
            ondemand)
                ondemand $1;;
            *)
                echod "$GOVERNOR: not enough setup"
                ;;
        esac
        ;;
esac
